### ISSUE TITLE
Example doesn't work as it lacks stripe_ui.dart

### ISSUE THREAD

**Issue by jainkunal** [ezet/stripe-sdk#132]
In the master branch the example doesn't work as it lacks `strip_ui.dart` mentioned in a few places. For Ex:
https://github.com/ezet/stripe-sdk/blob/04976ab3ef65f845ab0801865edec43338a67747/lib/src/ui/screens/add_payment_method_screen.dart#L10

**Comment by DmitriyYakovlev** [comment]
Yes, I have seen this today too((

**Comment by josxha** [comment]
Oh, I haven't seen this issue in time. I suggested in https://github.com/ezet/stripe-sdk/commit/200a1787bafc4981ffc3bb17a549a2892ed7baa3#r49808198 that the file might not have been added to the commit.
A temporary fix is to make the following changes to your `pubspec.yaml` file:
```yaml
dependencies:
   ...
   stripe_sdk: any
dependency_overrides:
   stripe_sdk:
      git:
        url: git://github.com/ezet/stripe-sdk.git
        ref: 617e34ce36bba3428a244525647522dd2e62a072

```
